<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPaoudek\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPaoudek/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPaoudek.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPaoudek\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPaoudek\appProdProjectContainer(array(
    'container.build_hash' => 'Paoudek',
    'container.build_id' => 'c0b77c42',
    'container.build_time' => 1539155770,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPaoudek');
